export const colors = {
  blue: "#2A3FFF",
  blueDark: "#1A2FE0",
  blueLight: "#4D5FFF",
  blueBg: "#EEF0FF",
  yellow: "#FFB800",
  yellowDark: "#E5A500",
  yellowLight: "#FFD54F",
  yellowBg: "#FFF8E1",
  ink: "#111827",
  muted: "#6b7280",
  line: "#e5e7eb",
  bg: "#f9fafb",
  white: "#ffffff",
  danger: "#ef4444",
  success: "#16a34a",
};

export const categories = [
  { id: "phones", name: "Phones & Tablets" },
  { id: "mobile-phones", name: "Mobile Phones" },
  { id: "tablets", name: "Tablets" },
  { id: "phone-accessories", name: "Phone Accessories" },
  { id: "smart-watches", name: "Smart Watches & Trackers" },
  { id: "headphones", name: "Headphones" },
  { id: "electronics", name: "Electronics" },
  { id: "computers", name: "Computers & Laptops" },
  { id: "laptops", name: "Laptops" },
  { id: "desktop-computers", name: "Desktop Computers" },
  { id: "computer-accessories", name: "Computer Accessories" },
  { id: "computer-hardware", name: "Computer Hardware" },
  { id: "computer-monitors", name: "Computer Monitors" },
  { id: "printers-scanners", name: "Printers & Scanners" },
  { id: "networking-products", name: "Networking Products" },
  { id: "software", name: "Software" },
  { id: "gadgets", name: "Gadgets" },
  { id: "tv-dvd", name: "TV & DVD Equipment" },
  { id: "tv-video", name: "TV & Video Equipment" },
  { id: "electronics-accessories", name: "Accessories & Supplies for Electronics" },
  { id: "audio-music", name: "Audio & Music Equipment" },
  { id: "cameras", name: "Cameras & Photo" },
  { id: "video-games", name: "Video Games & Consoles" },
  { id: "security-surveillance", name: "Security & Surveillance" },
  { id: "vehicles", name: "Cars & Vehicles" },
  { id: "cars", name: "Cars" },
  { id: "car-parts", name: "Car Parts & Accessories" },
  { id: "motorcycles", name: "Motorcycles & Scooters" },
  { id: "trucks", name: "Trucks & Trailers" },
  { id: "buses", name: "Buses & Microbuses" },
  { id: "heavy-equipment", name: "Heavy Equipment" },
  { id: "construction-heavy-machinery", name: "Construction & Heavy Machinery" },
  { id: "boats", name: "Boats & Watercraft" },
  { id: "personal-mobility", name: "Personal Mobility" },
  { id: "automotive-services", name: "Automotive Services" },
  { id: "real-estate", name: "Real Estate" },
  { id: "property", name: "Home Property & Apartments" },
  { id: "new-builds", name: "New Builds" },
  { id: "houses-sale", name: "Houses & Apartments for Sale" },
  { id: "houses-rent", name: "Houses & Apartments for Rent" },
  { id: "land-plots", name: "Land & Plots for Sale" },
  { id: "land-plots-rent", name: "Land & Plots for Rent" },
  { id: "commercial-property", name: "Commercial Property" },
  { id: "commercial-property-rent", name: "Commercial Property for Rent" },
  { id: "commercial-property-sale", name: "Commercial Property for Sale" },
  { id: "short-let", name: "Short Let Property" },
  { id: "rooms-shared", name: "Rooms & Shared Apartments" },
  { id: "event-centres", name: "Event Centres & Venues" },
  { id: "home-furniture-appliances", name: "Home, Furniture & Appliances" },
  { id: "furniture", name: "Furniture" },
  { id: "office-furniture", name: "Office Furniture" },
  { id: "home-appliances", name: "Home Appliances" },
  { id: "kitchen-appliances", name: "Kitchen Appliances" },
  { id: "kitchenware", name: "Kitchenware & Cookware" },
  { id: "home-accessories", name: "Home Accessories" },
  { id: "storage-organization", name: "Storage & Organization" },
  { id: "household-chemicals", name: "Household Chemicals" },
  { id: "garden", name: "Garden Supplies" },
  { id: "lighting", name: "Lighting" },
  { id: "bedding", name: "Bedding" },
  { id: "fashion", name: "Fashion" },
  { id: "womens-fashion", name: "Women's Fashion" },
  { id: "mens-fashion", name: "Men's Fashion" },
  { id: "baby-kids-fashion", name: "Baby & Kids Fashion" },
  { id: "clothing", name: "Clothing" },
  { id: "shoes", name: "Shoes" },
  { id: "bags", name: "Bags" },
  { id: "watches", name: "Watches" },
  { id: "jewelry", name: "Jewelry" },
  { id: "fashion-accessories", name: "Fashion Accessories" },
  { id: "wedding-wear", name: "Wedding Wear" },
  { id: "sportswear", name: "Sportswear" },
  { id: "beauty", name: "Beauty & Personal Care" },
  { id: "hair-beauty", name: "Hair Beauty" },
  { id: "face-care", name: "Face Care" },
  { id: "oral-care", name: "Oral Care" },
  { id: "body-care", name: "Body Care" },
  { id: "makeup", name: "Makeup" },
  { id: "skincare", name: "Skin Care" },
  { id: "fragrances", name: "Fragrances" },
  { id: "health-beauty-tools", name: "Health & Beauty Tools" },
  { id: "vitamins-supplements", name: "Vitamins & Supplements" },
  { id: "massagers", name: "Massagers" },
  { id: "jobs", name: "Jobs & Services" },
  { id: "accounting-jobs", name: "Accounting & Finance Jobs" },
  { id: "advertising-jobs", name: "Advertising & Marketing Jobs" },
  { id: "clerical-jobs", name: "Clerical & Administrative Jobs" },
  { id: "computing-jobs", name: "Computing & IT Jobs" },
  { id: "construction-jobs", name: "Construction & Skilled Trade Jobs" },
  { id: "customer-service-jobs", name: "Customer Service Jobs" },
  { id: "driver-jobs", name: "Driver Jobs" },
  { id: "engineering-jobs", name: "Engineering & Architecture Jobs" },
  { id: "healthcare-jobs", name: "Healthcare & Nursing Jobs" },
  { id: "hotel-jobs", name: "Hotel & Restaurant Jobs" },
  { id: "logistics-jobs", name: "Logistics & Transportation Jobs" },
  { id: "management-jobs", name: "Management Jobs" },
  { id: "manual-labour-jobs", name: "Manual Labour Jobs" },
  { id: "sales-jobs", name: "Sales & Telemarketing Jobs" },
  { id: "teaching-jobs", name: "Teaching Jobs" },
  { id: "seeking-work", name: "Seeking Work CVs" },
  { id: "services", name: "Services" },
  { id: "computer-it-services", name: "Computer & IT Services" },
  { id: "building-trades-services", name: "Building & Trades Services" },
  { id: "cleaning-services", name: "Cleaning Services" },
  { id: "repair-services", name: "Repair Services" },
  { id: "event-services", name: "Event Services" },
  { id: "health-beauty-services", name: "Health & Beauty Services" },
  { id: "legal-services", name: "Legal Services" },
  { id: "tax-financial-services", name: "Tax & Financial Services" },
  { id: "recruitment-services", name: "Recruitment Services" },
  { id: "rental-services", name: "Rental Services" },
  { id: "logistics-services", name: "Logistics & Courier Services" },
  { id: "chauffeur-airport", name: "Chauffeur & Airport Transfer Services" },
  { id: "manufacturing-services", name: "Manufacturing Services" },
  { id: "party-catering", name: "Party, Catering & Event Services" },
  { id: "printing-services", name: "Printing Services" },
  { id: "travel-agents", name: "Travel Agents & Tours" },
  { id: "tutoring", name: "Tutoring & Classes" },
  { id: "classes-courses", name: "Classes & Courses" },
  { id: "childcare-education", name: "Child Care & Education Services" },
  { id: "fitness-training", name: "Fitness & Personal Training Services" },
  { id: "dj-entertainment", name: "DJ & Entertainment Services" },
  { id: "wedding-services", name: "Wedding Venues & Services" },
  { id: "photography-video-services", name: "Photography & Video Services" },
  { id: "landscaping-gardening", name: "Landscaping & Gardening Services" },
  { id: "pet-services", name: "Pet Services" },
  { id: "writing-services", name: "Writing, Editing & Translation" },
  { id: "other-services", name: "Other Services" },
  { id: "repair-construction", name: "Repair & Construction" },
  { id: "building-materials", name: "Building Materials" },
  { id: "doors", name: "Doors" },
  { id: "electrical-equipment", name: "Electrical Equipment" },
  { id: "hand-tools", name: "Hand Tools" },
  { id: "measuring-tools", name: "Measuring Tools" },
  { id: "plumbing-water", name: "Plumbing & Water Supply" },
  { id: "solar-energy", name: "Solar Energy" },
  { id: "windows", name: "Windows" },
  { id: "commercial-equipment", name: "Commercial Equipment & Tools" },
  { id: "industrial-ovens", name: "Industrial Ovens" },
  { id: "manufacturing-equipment", name: "Manufacturing Equipment" },
  { id: "medical-equipment", name: "Medical Equipment" },
  { id: "restaurant-equipment", name: "Restaurant & Catering Equipment" },
  { id: "store-equipment", name: "Store Equipment" },
  { id: "printing-equipment", name: "Printing Equipment" },
  { id: "agriculture", name: "Food, Agriculture & Farming" },
  { id: "farm-machinery", name: "Farm Machinery & Equipment" },
  { id: "feeds-seeds", name: "Feeds, Supplements & Seeds" },
  { id: "livestock-poultry", name: "Livestock & Poultry" },
  { id: "meals-drinks", name: "Meals & Drinks" },
  { id: "farm-produce", name: "Farm Produce" },
  { id: "animals-pets", name: "Animals & Pets" },
  { id: "birds", name: "Birds" },
  { id: "cats", name: "Cats & Kittens" },
  { id: "dogs", name: "Dogs & Puppies" },
  { id: "fish", name: "Fish" },
  { id: "pet-accessories", name: "Pet Accessories" },
  { id: "other-animals", name: "Other Animals" },
  { id: "babies-kids", name: "Babies & Kids" },
  { id: "baby-accessories", name: "Babies & Kids Accessories" },
  { id: "baby-care", name: "Baby & Child Care" },
  { id: "children-clothing", name: "Children's Clothing" },
  { id: "children-furniture", name: "Children's Furniture" },
  { id: "children-shoes", name: "Children's Shoes" },
  { id: "maternity", name: "Maternity & Pregnancy" },
  { id: "strollers", name: "Prams & Strollers" },
  { id: "toys", name: "Toys" },
  { id: "leisure", name: "Leisure & Activities" },
  { id: "sports", name: "Sports & Fitness" },
  { id: "musical-instruments", name: "Musical Instruments" },
  { id: "books-games", name: "Books & Games" },
  { id: "camping-gear", name: "Camping Gear" },
  { id: "art-collectibles", name: "Art & Collectibles" },
  { id: "gym-fitness", name: "Gym & Fitness Equipment" },
  { id: "tickets", name: "Tickets" },
].sort((a, b) => a.name.localeCompare(b.name));

export const nigeriaStates = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT - Abuja",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
].sort((a, b) => a.localeCompare(b));

export function formatPrice(value: number) {
  return `NGN ${new Intl.NumberFormat("en-NG").format(value || 0)}`;
}

export function toWhatsappUrl(phone?: string | null) {
  if (!phone) return null;
  const normalized = phone.replace(/[^\d+]/g, "").replace(/^0/, "234");
  const withoutPlus = normalized.replace(/^\+/, "");
  return `https://wa.me/${withoutPlus}`;
}
